services:
  app:
    image: 'dcid/sumador:latest'
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=dcid
      - SPRING_DATASOURCE_PASSWORD=supersafepassword123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - 8080:8080
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=dcid
      - POSTGRES_PASSWORD=supersafepassword123
      - POSTGRES_DB=compose-postgres